project:
  type: website
  output-dir: docs
  resources:
    - CNAME

website:
  title: "Bethany Hamilton Bhat"
  site-url: "https://bhamiltonbhat.com"
  navbar:
    title: false
    left:
      - href: index.qmd
        text: Bethany Hamilton Bhat
      - href: presentations.qmd
        text: Presentations

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true



